{{- if .Values.secrets.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-catalog.fullname" . }}
  labels:
    {{- include "product-catalog.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.secrets.database.password | b64enc | quote }}
{{- end }}
