{{- if .Values.secrets.mongodb.uri }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-catalog.fullname" . }}
  labels:
    {{- include "product-catalog.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ .Values.secrets.mongodb.uri | b64enc | quote }}
{{- end }}
